DELETE FROM dogs;
DELETE FROM users;

insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (1, 'nphelan0', 'Natasha', 'Phelan', '73867 Division Center', '+421901234567', 'nphelan0@hc360.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (2, 'nkrink1', 'Nicolas', 'Krink', '5 Sherman Road', '+421902345678', 'nkrink1@booking.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (3, 'mbowkley2', 'Maurits', 'Bowkley', '4430 Charing Cross Hill', '+421903456789', 'mbowkley2@bandcamp.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (4, 'nwilliams3', 'Nil', 'Williams', '08 Kennedy Hill', '+421904567890', 'nwilliams3@nsw.gov.au');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (5, 'mbarwood4', 'Marisa', 'Barwood', '3890 Hoepker Road', '+421905678901', 'mbarwood4@addthis.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (6, 'tmahy5', 'Tremayne', 'Mahy', '7 Lillian Lane', '+421906789012', 'tmahy5@dell.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (7, 'csiemons6', 'Carlin', 'Siemons', '444 Nova Parkway', '+421907890123', 'csiemons6@taobao.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (8, 'gsponder7', 'Gregorius', 'Sponder', '3 West Trail', '+421908901234', 'gsponder7@dyndns.org');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (9, 'clippard8', 'Carleton', 'Lippard', '2 Ridge Oak Drive', '+421909012345', 'clippard8@samsung.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (10, 'vphython9', 'Valencia', 'Phython', '12528 Eagle Crest Crossing', '+421900123456', 'vphython9@infoseek.co.jp');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (11, 'akernesa', 'Alleyn', 'Kernes', '772 Arapahoe Way', '+421901234568', 'akernesa@ucsd.edu');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (12, 'bpoetzb', 'Ber', 'Poetz', '56 Riverside Lane', '+421902345679', 'bpoetzb@canalblog.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (13, 'arenisonc', 'Anton', 'Renison', '786 Heffernan Road', '+421903456780', 'arenisonc@telegraph.co.uk');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (14, 'bcrannad', 'Benn', 'Cranna', '26 Center Center', '+421904567891', 'bcrannad@is.gd');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (15, 'osetteringtone', 'Otes', 'Setterington', '6 Delladonna Avenue', '+421905678902', 'osetteringtone@vinaora.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (16, 'atrudgeonf', 'Alvan', 'Trudgeon', '72127 Vidon Center', '+421906789013', 'atrudgeonf@twitter.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (17, 'mkastelg', 'Mignon', 'Kastel', '9 Independence Circle', '+421907890124', 'mkastelg@cdc.gov');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (18, 'pvainesh', 'Penelopa', 'Vaines', '48630 Claremont Center', '+421908901235', 'pvainesh@feedburner.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (19, 'cibbotsoni', 'Calli', 'Ibbotson', '3404 Warbler Drive', '+421909012346', 'cibbotsoni@domainmarket.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (20, 'neglingtonj', 'Nanine', 'Eglington', '05894 Prairieview Park', '+421900123457', 'neglingtonj@noaa.gov');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (21, 'treynoldsonk', 'Tobias', 'Reynoldson', '3365 Harbort Parkway', '+421901234569', 'treynoldsonk@cornell.edu');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (22, 'gvasechkinl', 'Gay', 'Vasechkin', '569 Cambridge Pass', '+421902345670', 'gvasechkinl@paginegialle.it');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (23, 'ffreschim', 'Flem', 'Freschi', '63 Prairieview Point', '+421903456781', 'ffreschim@springer.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (24, 'mrottenburyn', 'Mary', 'Rottenbury', '222 Duke Crossing', '+421904567892', 'mrottenburyn@livejournal.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (25, 'tsherebrookeo', 'Toinette', 'Sherebrooke', '26 Nelson Alley', '+421905678903', 'tsherebrookeo@shinystat.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (26, 'djensonp', 'Dame', 'Jenson', '90551 Northfield Alley', '+421906789014', 'djensonp@amazon.co.jp');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (27, 'gpantoneq', 'Gare', 'Pantone', '5 Declaration Place', '+421907890125', 'gpantoneq@java.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (28, 'ahanmorer', 'Ardys', 'Hanmore', '9 Mitchell Junction', '+421908901236', 'ahanmorer@jiathis.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (29, 'rgooks', 'Reg', 'Gook', '55 Moland Circle', '+421909012347', 'rgooks@tinyurl.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (30, 'amcpharlaint', 'Alvis', 'McPharlain', '10 Almo Crossing', '+421900123458', 'amcpharlaint@exblog.jp');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (31, 'ediehnu', 'Evey', 'Diehn', '81071 Rutledge Hill', '+421901234570', 'ediehnu@ycombinator.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (32, 'sandreyv', 'Shannon', 'Andrey', '05243 Sundown Hill', '+421902345671', 'sandreyv@quantcast.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (33, 'nbacupw', 'Nelli', 'Bacup', '7318 Muir Trail', '+421903456782', 'nbacupw@gov.uk');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (34, 'jkarchewskix', 'Janina', 'Karchewski', '9047 Saint Paul Point', '+421904567893', 'jkarchewskix@arizona.edu');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (35, 'epostlesy', 'Erika', 'Postles', '635 Eggendart Place', '+421905678904', 'epostlesy@youtube.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (36, 'tizatz', 'Tanhya', 'Izat', '821 Crest Line Place', '+421906789015', 'tizatz@goodreads.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (37, 'kgeffen10', 'Kacie', 'Geffen', '9 La Follette Parkway', '+421907890126', 'kgeffen10@hostgator.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (38, 'sdipietro11', 'Suzi', 'Di Pietro', '90 Kennedy Parkway', '+421908901237', 'sdipietro11@deliciousdays.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (39, 'charston12', 'Callean', 'Harston', '4351 Reinke Pass', '+421909012348', 'charston12@abc.net.au');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (40, 'jcaudwell13', 'Jessee', 'Caudwell', '1037 Leroy Avenue', '+421900123459', 'jcaudwell13@answers.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (41, 'mmckune14', 'Maggie', 'McKune', '646 Dwight Hill', '+421901234571', 'mmckune14@elegantthemes.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (42, 'gpoge15', 'Gabe', 'Poge', '0208 Forest Dale Plaza', '+421902345672', 'gpoge15@slashdot.org');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (43, 'jvigus16', 'Jacinta', 'Vigus', '99626 Harbort Place', '+421903456783', 'jvigus16@wikia.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (44, 'cyve17', 'Cherri', 'Yve', '11 Sundown Terrace', '+421904567894', 'cyve17@ibm.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (45, 'drubega18', 'Darnall', 'Rubega', '9 Comanche Place', '+421905678905', 'drubega18@ca.gov');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (46, 'tbaxstair19', 'Taylor', 'Baxstair', '712 Express Crossing', '+421906789016', 'tbaxstair19@example.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (47, 'lkestle1a', 'Lorelle', 'Kestle', '4558 Springview Point', '+421907890127', 'lkestle1a@house.gov');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (48, 'bantonchik1b', 'Billye', 'Antonchik', '66 Sachtjen Court', '+421908901238', 'bantonchik1b@blogtalkradio.com');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (49, 'gniles1c', 'Guillermo', 'Niles', '43358 Delaware Trail', '+421909012349', 'gniles1c@gnu.org');
insert into users (userid, user_name, first_name, last_name, address, phone_number, email) values (50, 'sweatherburn1d', 'Salvatore', 'Weatherburn', '0956 International Street', '+421900123460', 'sweatherburn1d@google.pl');