DELETE FROM dogs;

insert into dogs (ownerId, name, breed, age) values (1, 'Lucy', 'Sibírsky husky', 14);
insert into dogs (ownerId, name, breed, age) values (2, 'Bailey', 'Beagle', 11);
insert into dogs (ownerId, name, breed, age) values (3, 'Zoe', 'Pudel', 4);
insert into dogs (ownerId, name, breed, age) values (4, 'Buddy', 'Bernský salašnícky pes', 15);
insert into dogs (ownerId, name, breed, age) values (5, 'Daisy', 'Pudel', 1);
insert into dogs (ownerId, name, breed, age) values (6, 'Luna', 'Boxer', 10);
insert into dogs (ownerId, name, breed, age) values (7, 'Sadie', 'Border collie', 6);
insert into dogs (ownerId, name, breed, age) values (8, 'Buddy', 'Boxer', 15);
insert into dogs (ownerId, name, breed, age) values (9, 'Lucy', 'Francúzsky buldoček', 8);
insert into dogs (ownerId, name, breed, age) values (10, 'Daisy', 'Čivava', 4);
insert into dogs (ownerId, name, breed, age) values (11, 'Cooper', 'Cavalier King Charles španiel', 1);
insert into dogs (ownerId, name, breed, age) values (12, 'Daisy', 'Golden Retriever', 11);
insert into dogs (ownerId, name, breed, age) values (13, 'Charlie', 'Rottweiler', 11);
insert into dogs (ownerId, name, breed, age) values (14, 'Buddy', 'Samoyed', 6);
insert into dogs (ownerId, name, breed, age) values (15, 'Zoe', 'Dalmatin', 10);
insert into dogs (ownerId, name, breed, age) values (16, 'Bella', 'Francúzsky buldoček', 10);
insert into dogs (ownerId, name, breed, age) values (17, 'Rex', 'Francúzsky buldoček', 10);
insert into dogs (ownerId, name, breed, age) values (18, 'Buddy', 'Rottweiler', 6);
insert into dogs (ownerId, name, breed, age) values (19, 'Zoe', 'Beagle', 10);
insert into dogs (ownerId, name, breed, age) values (20, 'Bailey', 'Nemecký ovčiak', 11);
insert into dogs (ownerId, name, breed, age) values (21, 'Bella', 'Rottweiler', 3);
insert into dogs (ownerId, name, breed, age) values (22, 'Toby', 'Shiba Inu', 4);
insert into dogs (ownerId, name, breed, age) values (23, 'Cooper', 'Pudel', 2);
insert into dogs (ownerId, name, breed, age) values (24, 'Max', 'Shiba Inu', 11);
insert into dogs (ownerId, name, breed, age) values (25, 'Rocky', 'Bernský salašnícky pes', 5);
insert into dogs (ownerId, name, breed, age) values (26, 'Luna', 'Boxer', 2);
insert into dogs (ownerId, name, breed, age) values (27, 'Rex', 'Akita', 8);
insert into dogs (ownerId, name, breed, age) values (28, 'Charlie', 'Pudel', 5);
insert into dogs (ownerId, name, breed, age) values (29, 'Luna', 'Čivava', 12);
insert into dogs (ownerId, name, breed, age) values (30, 'Charlie', 'Boxer', 14);
insert into dogs (ownerId, name, breed, age) values (31, 'Molly', 'Bernský salašnícky pes', 9);
insert into dogs (ownerId, name, breed, age) values (32, 'Duke', 'Corgi', 12);
insert into dogs (ownerId, name, breed, age) values (33, 'Lucy', 'Rottweiler', 15);
insert into dogs (ownerId, name, breed, age) values (34, 'Molly', 'Rottweiler', 8);
insert into dogs (ownerId, name, breed, age) values (35, 'Lucy', 'Border collie', 15);
insert into dogs (ownerId, name, breed, age) values (36, 'Zoe', 'Beagle', 6);
insert into dogs (ownerId, name, breed, age) values (37, 'Daisy', 'Doberman', 11);
insert into dogs (ownerId, name, breed, age) values (38, 'Bailey', 'Pudel', 6);
insert into dogs (ownerId, name, breed, age) values (39, 'Bailey', 'Corgi', 8);
insert into dogs (ownerId, name, breed, age) values (40, 'Chloe', 'Labrador', 11);
insert into dogs (ownerId, name, breed, age) values (41, 'Jack', 'Čivava', 10);
insert into dogs (ownerId, name, breed, age) values (42, 'Rocky', 'Bernský salašnícky pes', 12);
insert into dogs (ownerId, name, breed, age) values (43, 'Jack', 'Shiba Inu', 1);
insert into dogs (ownerId, name, breed, age) values (44, 'Max', 'Sibírsky husky', 6);
insert into dogs (ownerId, name, breed, age) values (45, 'Sadie', 'Sibírsky husky', 1);
insert into dogs (ownerId, name, breed, age) values (46, 'Daisy', 'Cavalier King Charles španiel', 9);
insert into dogs (ownerId, name, breed, age) values (47, 'Molly', 'Shiba Inu', 9);
insert into dogs (ownerId, name, breed, age) values (48, 'Bear', 'Boxer', 1);
insert into dogs (ownerId, name, breed, age) values (49, 'Toby', 'Golden Retriever', 4);
insert into dogs (ownerId, name, breed, age) values (50, 'Daisy', 'Rottweiler', 11);
