DELETE FROM dogs;

INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (1, 'Lucy', 'Sibírsky husky', 'female', 14);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (2, 'Bailey', 'Beagle', 'male', 11);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (3, 'Zoe', 'Pudel', 'female', 4);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (4, 'Buddy', 'Bernský salašnícky pes', 'male', 15);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (5, 'Daisy', 'Pudel', 'female', 1);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (6, 'Luna', 'Boxer', 'female', 10);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (7, 'Sadie', 'Border collie', 'female', 6);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (8, 'Buddy', 'Boxer', 'male', 15);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (9, 'Lucy', 'Francúzsky buldoček', 'female', 8);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (10, 'Daisy', 'Čivava', 'female', 4);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (11, 'Cooper', 'Cavalier King Charles španiel', 'male', 1);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (12, 'Daisy', 'Golden Retriever', 'female', 11);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (13, 'Charlie', 'Rottweiler', 'male', 11);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (14, 'Buddy', 'Samoyed', 'male', 6);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (15, 'Zoe', 'Dalmatin', 'female', 10);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (16, 'Bella', 'Francúzsky buldoček', 'female', 10);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (17, 'Rex', 'Francúzsky buldoček', 'male', 10);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (18, 'Buddy', 'Rottweiler', 'male', 6);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (19, 'Zoe', 'Beagle', 'female', 10);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (20, 'Bailey', 'Nemecký ovčiak', 'male', 11);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (21, 'Bella', 'Rottweiler', 'female', 3);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (22, 'Toby', 'Shiba Inu', 'male', 4);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (23, 'Cooper', 'Pudel', 'male', 2);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (24, 'Max', 'Shiba Inu', 'male', 11);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (25, 'Rocky', 'Bernský salašnícky pes', 'male', 5);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (26, 'Luna', 'Boxer', 'female', 2);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (27, 'Rex', 'Akita', 'male', 8);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (28, 'Charlie', 'Pudel', 'male', 5);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (29, 'Luna', 'Čivava', 'female', 12);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (30, 'Charlie', 'Boxer', 'male', 14);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (31, 'Molly', 'Bernský salašnícky pes', 'female', 9);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (32, 'Duke', 'Corgi', 'male', 12);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (33, 'Lucy', 'Rottweiler', 'female', 15);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (34, 'Molly', 'Rottweiler', 'female', 8);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (35, 'Lucy', 'Border collie', 'female', 15);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (36, 'Zoe', 'Beagle', 'female', 6);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (37, 'Daisy', 'Doberman', 'female', 11);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (38, 'Bailey', 'Pudel', 'male', 6);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (39, 'Bailey', 'Corgi', 'male', 8);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (40, 'Chloe', 'Labrador', 'female', 11);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (41, 'Jack', 'Čivava', 'male', 10);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (42, 'Rocky', 'Bernský salašnícky pes', 'male', 12);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (43, 'Jack', 'Shiba Inu', 'male', 1);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (44, 'Max', 'Sibírsky husky', 'male', 6);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (45, 'Sadie', 'Sibírsky husky', 'female', 1);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (46, 'Daisy', 'Cavalier King Charles španiel', 'female', 9);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (47, 'Molly', 'Shiba Inu', 'female', 9);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (48, 'Bear', 'Boxer', 'male', 1);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (49, 'Toby', 'Golden Retriever', 'male', 4);
INSERT INTO dogs (ownerId, name, breed, sex, age) VALUES (50, 'Daisy', 'Rottweiler', 'female', 11);