CREATE TABLE dogs
(
    dogid   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ownerid VARCHAR(255),
    name    VARCHAR(255),
    breed   VARCHAR(255),
    sex     VARCHAR(6),
    age     INTEGER                                  NOT NULL,
    CONSTRAINT pk_dogs PRIMARY KEY (dogid)
);

ALTER TABLE dogs
    ADD CONSTRAINT FK_DOGS_ON_OWNERID FOREIGN KEY (ownerid) REFERENCES users (userid);