CREATE TABLE answers
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    question_id INTEGER,
    answer      VARCHAR(255),
    votes       INTEGER,
    is_best_one BOOLEAN,
    answerer_id VARCHAR(255),
    answered_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_answers PRIMARY KEY (id)
);

CREATE TABLE questions
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    question      VARCHAR(255),
    questioner_id VARCHAR(255),
    closed        BOOLEAN,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_questions PRIMARY KEY (id)
);

CREATE TABLE trainings
(
    trainingid                     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    training_name                  VARCHAR(255),
    training_type                  VARCHAR(255),
    training_date_time             TIMESTAMP WITHOUT TIME ZONE,
    count_of_training_participants INTEGER,
    CONSTRAINT pk_trainings PRIMARY KEY (trainingid)
);

ALTER TABLE questions
    ADD CONSTRAINT uc_questions_questioner UNIQUE (questioner_id);

ALTER TABLE answers
    ADD CONSTRAINT FK_ANSWERS_ON_ANSWERER FOREIGN KEY (answerer_id) REFERENCES users (userid);

ALTER TABLE answers
    ADD CONSTRAINT FK_ANSWERS_ON_QUESTION FOREIGN KEY (question_id) REFERENCES questions (id);

ALTER TABLE questions
    ADD CONSTRAINT FK_QUESTIONS_ON_QUESTIONER FOREIGN KEY (questioner_id) REFERENCES users (userid);

CREATE TABLE training_participants (
                                       id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       trainingid INTEGER NOT NULL,
                                       userid     VARCHAR(255) NOT NULL,
                                       role        VARCHAR(64),

                                       CONSTRAINT fk_tp_training
                                           FOREIGN KEY (trainingid) REFERENCES trainings (trainingid),
                                       CONSTRAINT fk_tp_user
                                           FOREIGN KEY (userid) REFERENCES users (userid)
);