/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CalendarAndReturnButton: typeof import('./src/components/CalendarAndReturnButton.vue')['default']
    EditProfileView: typeof import('./src/views/EditProfileView.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    Logout: typeof import('./src/components/Logout.vue')['default']
    NewTrainingFirstStep: typeof import('./src/components/NewTrainingFirstStep.vue')['default']
    NewTrainingSecondStep: typeof import('./src/components/NewTrainingSecondStep.vue')['default']
    ProfileForTraining: typeof import('./src/components/ProfileForTraining.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TrainingsAndLogout: typeof import('./src/components/TrainingsAndLogout.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
  }
}

// For TSX support
declare global {
  const CalendarAndReturnButton: typeof import('./src/components/CalendarAndReturnButton.vue')['default']
  const EditProfileView: typeof import('./src/views/EditProfileView.vue')['default']
  const ElAvatar: typeof import('element-plus/es')['ElAvatar']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElPopover: typeof import('element-plus/es')['ElPopover']
  const Logout: typeof import('./src/components/Logout.vue')['default']
  const NewTrainingFirstStep: typeof import('./src/components/NewTrainingFirstStep.vue')['default']
  const NewTrainingSecondStep: typeof import('./src/components/NewTrainingSecondStep.vue')['default']
  const ProfileForTraining: typeof import('./src/components/ProfileForTraining.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TrainingsAndLogout: typeof import('./src/components/TrainingsAndLogout.vue')['default']
  const UserProfile: typeof import('./src/components/UserProfile.vue')['default']
}