@realm = dog-master-realm
@username = harry.potter
@password = Start123

###
POST http://localhost:9099/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type = password
    &
client_id = dog-master-client
    &
username = {{username}}
    &
password = {{password}}

> {%
    // noinspection JSUnresolvedReference
    client.global.set("user_access_token", response.body.access_token);
%}

###
POST http://localhost:8081/api/v1/trainings
Content-Type: application/json
Authorization: Bearer {{user_access_token}}

{
  "trainingtype": "INDIVIDUAL",
  "trainingsNames": "protection,footage",
  "date": "2026-02-08"
}